version: '3.7'

networks:
  front:
    name: front
  back:
    name: back

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
    networks:
      - back
      - front

  mariadb:
    image: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - "3306:3306"
    networks:
      - back
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  liquibase:
    image: liquibase/liquibase:4.26-alpine
    command: update --url=jdbc:mariadb://mariadb:3306/${DB_NAME} --changeLogFile=changelog.yml --username=${DB_USER} --password=${DB_PWD}
    volumes:
      - ./liquibase/changelog/changelog.yml:/liquibase/changelog.yml # ./liquibase/changelog/changelog.yml:/liquibase/changelog/changelog.yml (working on Windows)
      - ./liquibase/scripts:/liquibase/scripts
    networks:
      - back
    depends_on:
      mariadb:
        condition: service_healthy

  backend:
    image: marepal631/tai_backend # backend:0.0.4
    restart: always
    volumes:
      - backend-data:/app/songs
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - back

  frontend:
    image: marepal631/tai_frontend
    restart: always
    environment:
      TAI_API_URL: http://localhost:8080/
      TAI_GOOGLE_CLIENT_ID: 973777854173-pr4vohi6sv2ve94r2bj8ta8q69vlbq9u.apps.googleusercontent.com
      TAI_GOOGLE_CLIENT_SECRET: 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
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - front

volumes:
  mariadb-data:
  backend-data: